<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Admins-MacBook-Pro.local" failures="0" tests="6" name="com.ugapp.testcases.TC_05_PreAppDashboardTest" time="22.352" errors="1" timestamp="2024-09-15T23:51:48 IST" skipped="0">
  <testcase classname="com.ugapp.testcases.TC_05_PreAppDashboardTest" name="tearDown" time="0.033">
    <error message="/ by zero" type="java.lang.ArithmeticException">
      <![CDATA[java.lang.ArithmeticException: / by zero
at com.ugapp.listeners.CustomListeners.onFinish(CustomListeners.java:148)
at com.ugapp.testcases.SlackIntegration.testSlackIntegration(SlackIntegration.java:26)
at com.ugapp.testcases.BaseTest.tearDown(BaseTest.java:179)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:410)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- tearDown -->
  <testcase classname="com.ugapp.testcases.TC_05_PreAppDashboardTest" name="validatePreAppSubmissionPage" time="1.557"/>
  <testcase classname="com.ugapp.testcases.TC_05_PreAppDashboardTest" name="PreAppDashboardNames" time="6.124"/>
  <testcase classname="com.ugapp.testcases.TC_05_PreAppDashboardTest" name="BirthdayAge_Greater24Test" time="5.015"/>
  <testcase classname="com.ugapp.testcases.TC_05_PreAppDashboardTest" name="PhoneNumberTest" time="3.435"/>
  <testcase classname="com.ugapp.testcases.TC_05_PreAppDashboardTest" name="StartNewAppTest" time="6.188"/>
</testsuite> <!-- com.ugapp.testcases.TC_05_PreAppDashboardTest -->
