<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Admins-MacBook-Pro.local" failures="0" tests="7" name="com.ugapp.testcases.TC_15_ReviewTest" time="118.158" errors="1" timestamp="24 Jan 2024 11:58:29 GMT" skipped="0">
  <testcase classname="com.ugapp.testcases.TC_15_ReviewTest" name="review" time="7.550"/>
  <testcase classname="com.ugapp.testcases.TC_15_ReviewTest" name="writeReview" time="21.375"/>
  <testcase classname="com.ugapp.testcases.TC_15_ReviewTest" name="CompareValidWithReview" time="0.159"/>
  <testcase classname="com.ugapp.testcases.TC_15_ReviewTest" name="edit" time="27.275"/>
  <testcase classname="com.ugapp.testcases.TC_15_ReviewTest" name="ApplicationAffidavitTest" time="2.576">
    <error message="Cannot invoke &quot;org.openqa.selenium.WebElement.click()&quot; because the return value of &quot;com.ugapp.pages.ReviewPage.findElement(String)&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebElement.click()" because the return value of "com.ugapp.pages.ReviewPage.findElement(String)" is null
	at com.ugapp.pages.ReviewPage.ApplicationAffidavit(ReviewPage.java:416)
	at com.ugapp.testcases.TC_15_ReviewTest.ApplicationAffidavitTest(TC_15_ReviewTest.java:91)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- ApplicationAffidavitTest -->
  <testcase classname="com.ugapp.testcases.TC_15_ReviewTest" name="AcknowledgementTest" time="3.095"/>
  <testcase classname="com.ugapp.testcases.TC_15_ReviewTest" name="ApplicationFee_VisaTest" time="56.128"/>
</testsuite> <!-- com.ugapp.testcases.TC_15_ReviewTest -->
